{
  "affected_release": [
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "release_date": "2023-11-07T00:00:00Z",
      "advisory": "RHSA-2023:6583",
      "package": "kernel-0:5.14.0-362.8.1.el9_3",
      "cpe": "cpe:/a:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "release_date": "2023-11-07T00:00:00Z",
      "advisory": "RHSA-2023:6583",
      "package": "kernel-0:5.14.0-362.8.1.el9_3",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Out of support scope",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Fix deferred",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2025-03-27T00:00:00Z",
  "bugzilla": {
    "description": "kernel: ALSA: hda/via: Avoid potential array out-of-bound in add_secret_dac_path()",
    "id": "2355431",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2355431"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "6.0",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:H/UI:N/S:U/C:H/I:N/A:H",
    "status": "verified"
  },
  "iava": "",
  "cwe": "CWE-129",
  "statement": "Red Hat rated this vulnerability with a MODERATE impact because an attacker would need access to load/manipulate ALSA codec data, which requires elevated privileges.",
  "acknowledgement": "",
  "name": "CVE-2023-52988",
  "document_distribution": "",
  "details": [
    "In the Linux kernel, the following vulnerability has been resolved:\nALSA: hda/via: Avoid potential array out-of-bound in add_secret_dac_path()\nsnd_hda_get_connections() can return a negative error code.\nIt may lead to accessing 'conn' array at a negative index.\nFound by Linux Verification Center (linuxtesting.org) with SVACE.",
    "A vulnerability was found in the Linux kernel's ALSA subsystem in the `add_secret_dac_path()` function, where improper array handling can lead to out-of-bounds access. This occurs if the return value of the call to `snd_hda_get_connections()` returns an error code (a negative number), which is stored in the variable `nums` that is then used as the upper bound of a for loop used to access the `conn` structure. This issue could lead to undefined behavior or a memory crash due to invalid memory access."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2023-52988\nhttps://nvd.nist.gov/vuln/detail/CVE-2023-52988\nhttps://lore.kernel.org/linux-cve-announce/2025032708-CVE-2023-52988-5520@gregkh/T"
  ]
}