{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux AI (RHEL AI)",
      "fix_state": "Affected",
      "package_name": "com.nvidia.cuda.com.nvidia.cuda.core",
      "cpe": "cpe:/a:redhat:enterprise_linux_ai:1"
    },
    {
      "product_name": "Red Hat Enterprise Linux AI (RHEL AI)",
      "fix_state": "Affected",
      "package_name": "com.nvidia.cuda.com.nvidia.cuda.debug.core",
      "cpe": "cpe:/a:redhat:enterprise_linux_ai:1"
    },
    {
      "product_name": "Red Hat Enterprise Linux AI (RHEL AI)",
      "fix_state": "Affected",
      "package_name": "com.nvidia.cuda.com.nvidia.cuda.debug.ui",
      "cpe": "cpe:/a:redhat:enterprise_linux_ai:1"
    },
    {
      "product_name": "Red Hat Enterprise Linux AI (RHEL AI)",
      "fix_state": "Affected",
      "package_name": "com.nvidia.cuda.com.nvidia.cuda.docker.launch",
      "cpe": "cpe:/a:redhat:enterprise_linux_ai:1"
    },
    {
      "product_name": "Red Hat Enterprise Linux AI (RHEL AI)",
      "fix_state": "Affected",
      "package_name": "com.nvidia.cuda.com.nvidia.cuda.profile.ui",
      "cpe": "cpe:/a:redhat:enterprise_linux_ai:1"
    },
    {
      "product_name": "Red Hat Enterprise Linux AI (RHEL AI)",
      "fix_state": "Affected",
      "package_name": "com.nvidia.cuda.com.nvidia.cuda.remote.launch",
      "cpe": "cpe:/a:redhat:enterprise_linux_ai:1"
    },
    {
      "product_name": "Red Hat Enterprise Linux AI (RHEL AI)",
      "fix_state": "Affected",
      "package_name": "com.nvidia.cuda.com.nvidia.cuda.telemetry",
      "cpe": "cpe:/a:redhat:enterprise_linux_ai:1"
    },
    {
      "product_name": "Red Hat Enterprise Linux AI (RHEL AI)",
      "fix_state": "Affected",
      "package_name": "com.nvidia.cuda.com.nvidia.cuda.toolchain",
      "cpe": "cpe:/a:redhat:enterprise_linux_ai:1"
    },
    {
      "product_name": "Red Hat Enterprise Linux AI (RHEL AI)",
      "fix_state": "Affected",
      "package_name": "com.nvidia.cuda.com.nvidia.cuda.toolchain.doc.user",
      "cpe": "cpe:/a:redhat:enterprise_linux_ai:1"
    },
    {
      "product_name": "Red Hat Enterprise Linux AI (RHEL AI)",
      "fix_state": "Affected",
      "package_name": "com.nvidia.cuda.com.nvidia.cuda.ui",
      "cpe": "cpe:/a:redhat:enterprise_linux_ai:1"
    },
    {
      "product_name": "Red Hat Enterprise Linux AI (RHEL AI)",
      "fix_state": "Affected",
      "package_name": "com.nvidia.cuda.ide.com.nvidia.cuda.ide.editor",
      "cpe": "cpe:/a:redhat:enterprise_linux_ai:1"
    },
    {
      "product_name": "Red Hat Enterprise Linux AI (RHEL AI)",
      "fix_state": "Affected",
      "package_name": "com.nvidia.cuda.ide.com.nvidia.cuda.ide.remote.connection",
      "cpe": "cpe:/a:redhat:enterprise_linux_ai:1"
    },
    {
      "product_name": "Red Hat Enterprise Linux AI (RHEL AI)",
      "fix_state": "Affected",
      "package_name": "cuda.cuda",
      "cpe": "cpe:/a:redhat:enterprise_linux_ai:1"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2024-08-31T09:15:06Z",
  "bugzilla": {
    "description": "NVIDIA CUDA Toolkit: Denial of service in NVIDIA CUDA",
    "id": "2308800",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2308800"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "4.4",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:L",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-1284",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2024-0111",
  "document_distribution": "",
  "details": [
    "NVIDIA CUDA Toolkit contains a vulnerability in command 'cuobjdump' where a user may cause a crash or produce incorrect output by passing a malformed ELF file. A successful exploit of this vulnerability may lead to a limited denial of service or data tampering."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2024-0111\nhttps://nvd.nist.gov/vuln/detail/CVE-2024-0111\nhttps://nvidia.custhelp.com/app/answers/detail/a_id/5564"
  ]
}