{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Fix deferred",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Fix deferred",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2025-05-01T00:00:00Z",
  "bugzilla": {
    "description": "kernel: tracing: Fix memory leak in tracing_read_pipe()",
    "id": "2363397",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2363397"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2022-49801",
  "document_distribution": "",
  "details": [
    "In the Linux kernel, the following vulnerability has been resolved:\ntracing: Fix memory leak in tracing_read_pipe()\nkmemleak reports this issue:\nunreferenced object 0xffff888105a18900 (size 128):\ncomm \"test_progs\", pid 18933, jiffies 4336275356 (age 22801.766s)\nhex dump (first 32 bytes):\n25 73 00 90 81 88 ff ff 26 05 00 00 42 01 58 04  %s......\u0026...B.X.\n03 00 00 00 02 00 00 00 00 00 00 00 00 00 00 00  ................\nbacktrace:\n[\u003c00000000560143a1\u003e] __kmalloc_node_track_caller+0x4a/0x140\n[\u003c000000006af00822\u003e] krealloc+0x8d/0xf0\n[\u003c00000000c309be6a\u003e] trace_iter_expand_format+0x99/0x150\n[\u003c000000005a53bdb6\u003e] trace_check_vprintf+0x1e0/0x11d0\n[\u003c0000000065629d9d\u003e] trace_event_printf+0xb6/0xf0\n[\u003c000000009a690dc7\u003e] trace_raw_output_bpf_trace_printk+0x89/0xc0\n[\u003c00000000d22db172\u003e] print_trace_line+0x73c/0x1480\n[\u003c00000000cdba76ba\u003e] tracing_read_pipe+0x45c/0x9f0\n[\u003c0000000015b58459\u003e] vfs_read+0x17b/0x7c0\n[\u003c000000004aeee8ed\u003e] ksys_read+0xed/0x1c0\n[\u003c0000000063d3d898\u003e] do_syscall_64+0x3b/0x90\n[\u003c00000000a06dda7f\u003e] entry_SYSCALL_64_after_hwframe+0x63/0xcd\niter-\u003efmt alloced in\ntracing_read_pipe() -\u003e .. -\u003etrace_iter_expand_format(), but not\nfreed, to fix, add free in tracing_release_pipe()"
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2022-49801\nhttps://nvd.nist.gov/vuln/detail/CVE-2022-49801\nhttps://lore.kernel.org/linux-cve-announce/2025050126-CVE-2022-49801-2191@gregkh/T"
  ]
}